#PBS -lwalltime=05:00:00
#PBS -lselect=1:ncpus=2:mem=24gb:ngpus=2:gpu_type=RTX6000:cpu_type=skylake
#PBS -o test.out 
#PBS -e test.err 

module load anaconda3/personal
module load cuda/11.2.2
module load cudnn/8.2.4
source activate msc

python $HOME/msc/UNETR/main.py --feature_size=32 --batch_size=6 --logdir=$HOME/msc/UNETR/unetr_test --optim_lr=2e-4 --lrschedule=warmup_cosine --infer_overlap=0.5 --save_checkpoint --data_dir=$HOME/datasets/BTCV/ --workers=1 --distributed --save_checkpoint